import time
from pynput import keyboard
keyboard_controller = keyboard.Controller()

pause:float = .2175

def bardsAdventure():
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('qv')
    time.sleep(pause * 8)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('w')
    time.sleep(pause * 1)
    keyboard_controller.type('jb')
    time.sleep(pause * 2)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('j')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 5)
    keyboard_controller.type('g')
    time.sleep(pause * 1)
    keyboard_controller.type('dn')
    time.sleep(pause * 11)
    keyboard_controller.type('an')
    time.sleep(pause * 7)

    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('j')
    time.sleep(pause * 1)
    keyboard_controller.type('qv')
    time.sleep(pause * 3)
    keyboard_controller.type('sj')
    time.sleep(pause * 3)
    keyboard_controller.type('ah')
    time.sleep(pause * 3)
    keyboard_controller.type('hb')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('w')
    time.sleep(pause * 2)
    keyboard_controller.type('gm')
    time.sleep(pause * 11)

    keyboard_controller.type('jv')
    time.sleep(pause * 1)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('hv')
    time.sleep(pause * 1)
    keyboard_controller.type('jv')
    time.sleep(pause * 1)
    keyboard_controller.type('qv')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('jv')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('e')
    time.sleep(pause * 1)
    keyboard_controller.type('wv')
    time.sleep(pause * 1)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('jv')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('jv')
    time.sleep(pause * 1)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('jv')
    time.sleep(pause * 1)
    keyboard_controller.type('qv')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('jv')
    time.sleep(pause * 1)
    keyboard_controller.type('qv')
    time.sleep(pause * 1)
    keyboard_controller.type('tv')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 3)

    keyboard_controller.type('d')
    time.sleep(pause * 1)
    keyboard_controller.type('g')
    time.sleep(pause * 1)
    keyboard_controller.type('hv')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('a')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('j')
    time.sleep(pause * 1)
    keyboard_controller.type('qv')
    time.sleep(pause * 1)
    keyboard_controller.type('wv')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('a')
    time.sleep(pause * 1)
    keyboard_controller.type('ev')
    time.sleep(pause * 1)
    keyboard_controller.type('w')
    time.sleep(pause * 1)
    keyboard_controller.type('qv')
    time.sleep(pause * 1)
    keyboard_controller.type('j')
    time.sleep(pause * 1)
    keyboard_controller.type('qv')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('a')
    time.sleep(pause * 1)
    keyboard_controller.type('a')
    time.sleep(pause * 1)
    keyboard_controller.type('aj')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('jv')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('m')
    time.sleep(pause * 1)
    keyboard_controller.type('g')
    time.sleep(pause * 1)
    keyboard_controller.type('m')
    time.sleep(pause * 1)
    keyboard_controller.type('m')
    time.sleep(pause * 1)
    keyboard_controller.type('m')
    time.sleep(pause * 1)
    keyboard_controller.type('hx')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('hn')
    time.sleep(pause * 1)
    keyboard_controller.type('j')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('gv')
    time.sleep(pause * 1)
    keyboard_controller.type('f')
    time.sleep(pause * 1)
    keyboard_controller.type('a')
    time.sleep(pause * 1)
    keyboard_controller.type('f')
    time.sleep(pause * 1)
    keyboard_controller.type('dv')
    time.sleep(pause * 1)
    keyboard_controller.type('sn')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('j')
    time.sleep(pause * 1)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('wn')
    time.sleep(pause * 1)
    keyboard_controller.type('wn')
    time.sleep(pause * 1)
    keyboard_controller.type('wn')
    time.sleep(pause * 1)
    keyboard_controller.type('en')
    time.sleep(pause * 1)
    keyboard_controller.type('hn')
    time.sleep(pause * 1)
    keyboard_controller.type('hv')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('j')
    time.sleep(pause * 1)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('wb')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('es')
    time.sleep(pause * 1)
    keyboard_controller.type('w')
    time.sleep(pause * 1)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('j')
    time.sleep(pause * 1)
    keyboard_controller.type('qn')
    time.sleep(pause * 1)
    keyboard_controller.type('d')
    time.sleep(pause * 1)
    keyboard_controller.type('j')
    time.sleep(pause * 1)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('d')
    time.sleep(pause * 1)
    keyboard_controller.type('j')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('jb')
    time.sleep(pause * 1)
    keyboard_controller.type('m')
    time.sleep(pause * 1)
    keyboard_controller.type('a')
    time.sleep(pause * 1)
    keyboard_controller.type('g')
    time.sleep(pause * 1)
    keyboard_controller.type('m')
    time.sleep(pause * 1)
    keyboard_controller.type('a')
    time.sleep(pause * 1)
    keyboard_controller.type('m')
    time.sleep(pause * 1)
    keyboard_controller.type('hv')
    time.sleep(pause * 2)
    keyboard_controller.type('v')
    time.sleep(pause * 2)
    keyboard_controller.type('gv')
    time.sleep(pause * 1)
    keyboard_controller.type('f')
    time.sleep(pause * 1)
    keyboard_controller.type('dz')
    time.sleep(pause * 1)
    keyboard_controller.type('g')
    time.sleep(pause * 1)
    keyboard_controller.type('z')
    time.sleep(pause * 1)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('ez')
    time.sleep(pause * 1)
    keyboard_controller.type('wx')
    time.sleep(pause * 1)
    keyboard_controller.type('b')
    time.sleep(pause * 1)
    keyboard_controller.type('gx')
    time.sleep(pause * 1)
    keyboard_controller.type('b')
    time.sleep(pause * 1)
    keyboard_controller.type('gx')
    time.sleep(pause * 1)
    keyboard_controller.type('b')
    time.sleep(pause * 1)
    keyboard_controller.type('hx')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 2)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('hn')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('gn')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('jx')
    time.sleep(pause * 1)
    keyboard_controller.type('m')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('m')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('m')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('m')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('a')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('af')
    time.sleep(pause * 1)
    keyboard_controller.type('hx')
    time.sleep(pause * 1)
    keyboard_controller.type('a')
    time.sleep(pause * 1)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('ra')
    time.sleep(pause * 1)
    keyboard_controller.type('ex')
    time.sleep(pause * 1)
    keyboard_controller.type('b')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('rb')
    time.sleep(pause * 1)
    keyboard_controller.type('e')
    time.sleep(pause * 1)
    keyboard_controller.type('wx')
    time.sleep(pause * 1)
    keyboard_controller.type('b')
    time.sleep(pause * 1)
    keyboard_controller.type('x')
    time.sleep(pause * 1)
    keyboard_controller.type('g')
    time.sleep(pause * 1)
    keyboard_controller.type('jb')
    time.sleep(pause * 1)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('wx')
    time.sleep(pause * 1)
    keyboard_controller.type('hx')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('sx')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('qx')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('sx')
    time.sleep(pause * 1)
    keyboard_controller.type('b')
    time.sleep(pause * 1)
    keyboard_controller.type('jx')
    time.sleep(pause * 1)
    keyboard_controller.type('b')
    time.sleep(pause * 1)
    keyboard_controller.type('sx')
    time.sleep(pause * 1)
    keyboard_controller.type('gb')
    time.sleep(pause * 1)
    keyboard_controller.type('sx')
    time.sleep(pause * 1)
    keyboard_controller.type('jb')
    time.sleep(pause * 1)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('ws')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('s')
    time.sleep(pause * 1)
    keyboard_controller.type('jx')
    time.sleep(pause * 1)
    keyboard_controller.type('jx')
    time.sleep(pause * 1)
    keyboard_controller.type('jx')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('j')
    time.sleep(pause * 1)
    keyboard_controller.type('qv')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('qv')
    time.sleep(pause * 1)
    keyboard_controller.type('w')
    time.sleep(pause * 1)
    keyboard_controller.type('jb')
    time.sleep(pause * 1)
    keyboard_controller.type('hb')
    time.sleep(pause * 1)
    keyboard_controller.type('b')
    time.sleep(pause * 1)
    keyboard_controller.type('b')
    time.sleep(pause * 1)
    keyboard_controller.type('gb')
    time.sleep(pause * 1)
    keyboard_controller.type('hn')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('e')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('hn')
    time.sleep(pause * 1)
    keyboard_controller.type('n')
    time.sleep(pause * 1)
    keyboard_controller.type('j')
    time.sleep(pause * 1)
    keyboard_controller.type('qv')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('v')
    time.sleep(pause * 1)
    keyboard_controller.type('qv')
    time.sleep(pause * 1)
    keyboard_controller.type('w')
    time.sleep(pause * 1)
    keyboard_controller.type('q')
    time.sleep(pause * 1)
    keyboard_controller.type('jb')
    time.sleep(pause * 1)
    keyboard_controller.type('hb')
    time.sleep(pause * 1)
    keyboard_controller.type('b')
    time.sleep(pause * 1)
    keyboard_controller.type('b')
    time.sleep(pause * 1)
    keyboard_controller.type('gb')
    time.sleep(pause * 1)
    keyboard_controller.type('hn')
    time.sleep(pause * 1)
    keyboard_controller.type('hn')
    time.sleep(pause * 1)
    keyboard_controller.type('en')
    time.sleep(pause * 1)
    keyboard_controller.type('hn')
    time.sleep(pause * 1)
    keyboard_controller.type('en')
    time.sleep(pause * 1)
    keyboard_controller.type('wn')
    time.sleep(pause * 1)
    keyboard_controller.type('hn')
    time.sleep(pause * 1)
    keyboard_controller.type('wn')
    time.sleep(pause * 1)
    keyboard_controller.type('hn')
    time.sleep(pause * 1)
    keyboard_controller.type('wn')
    time.sleep(pause * 1)
    keyboard_controller.type('h')
    time.sleep(pause * 1)
    keyboard_controller.type('en')
    time.sleep(pause * 1)
    keyboard_controller.type('en')