import time
from pynput import keyboard
keyboard_controller = keyboard.Controller()

pause:float = .25

def tinyLight():
    keyboard_controller.type('q')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 3)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 3)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 4)

    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 3)
    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 3)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 4)

    keyboard_controller.type('q')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 3)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 3)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 4)

    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('m')
    time.sleep(pause * 2)
    keyboard_controller.type('m')
    time.sleep(pause * 3)
    keyboard_controller.type('a')
    time.sleep(pause * 4)

    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 4)

    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('m')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('a')
    time.sleep(pause * 4)

    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('a')
    time.sleep(pause * 2)
    keyboard_controller.type('a')
    time.sleep(pause * 4)

    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 4)

    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 3)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 6)



    keyboard_controller.type('q')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 3)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 4)

    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 4)

    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('w')
    time.sleep(pause * 2)
    keyboard_controller.type('w')
    time.sleep(pause * 4)

    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 4)

    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)

    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 3)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('q')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 4)

    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('e')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 4)

    keyboard_controller.type('q')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 3)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 4)

    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 4)

    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 3)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('w')
    time.sleep(pause * 2)
    keyboard_controller.type('w')
    time.sleep(pause * 4)

    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 4)

    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 4)

    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('q')
    time.sleep(pause * 2)
    keyboard_controller.type('e')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 4)

    keyboard_controller.type('s')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('w')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('j')
    time.sleep(pause * 4)

    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('g')
    time.sleep(pause * 2)
    keyboard_controller.type('h')
    time.sleep(pause * 2)
    keyboard_controller.type('d')
    time.sleep(pause * 2)
    keyboard_controller.type('f')
    time.sleep(pause * 2)
    keyboard_controller.type('g')